#  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html
spring:
  jpa:
    open-in-view: false
    show-sql: true
    hibernate:
      ddl-auto: create-drop
    properties:
      #  http://docs.jboss.org/hibernate/orm/5.3/userguide/html_single/Hibernate_User_Guide.html#configurations
      hibernate:
        format_sql: true
        #  https://access.redhat.com/documentation/en-us/jboss_enterprise_application_platform/5/html/performance_tuning_guide/sect-performance_tuning_guide-entity_beans-batching_database_operations
        default_batch_fetch_size: 20
        jdbc.batch_size: 20
  #     jdbc.fetch_size: 20
  datasource:
    # ImMemory
    url: jdbc:h2:mem:voting
    #   tcp: jdbc:h2:tcp://localhost:9092/mem:voting
    # Absolute path
    #    url: jdbc:h2:C:/projects/hyperjava/restorant-voting/db/voting
    #    tcp:     jdbc:h2:tcp://localhost:9092/C:/projects/hyperjava/restorant-voting/db/voting
    #    offline: jdbc:h2:C:/projects/hyperjava/restorant-voting/db/voting
    # Relative path1
    #    url: jdbc:h2:./db/voting
    #    tcp, offline: absolute path
    # Relative path2
    #    url: jdbc:h2:~/voting
    #    tcp:     jdbc:h2:tcp://localhost:9092/~/voting
    #    offline: jdbc:h2:~/voting
    username: sa
    password:
  h2.console.enabled: true

  data.rest:
    #  https://docs.spring.io/spring-data/rest/docs/current/reference/html/#getting-started.basic-settings
    basePath: /api
    defaultPageSize: 20
    returnBodyOnCreate: true

  mvc.date-format: yyyy-MM-dd

  #  https://docs.spring.io/spring-boot/docs/current/reference/html/common-application-properties.html#common-application-properties-security
  security:
    user:
      name: user
      password: password
      roles: USER

logging.level.org.springframework.security.web.FilterChainProxy: DEBUG
